# 分布式事务配置
seata:
  tx-service-group: mall_tx_group
  enable-auto-data-source-proxy: true
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.112.130:8848,192.168.112.131:8848
      namespace: seata_namespace_id
      group: SEATA_GROUP
  config:
    type: nacos
    nacos:
      server-addr: 192.168.112.130:8848,192.168.112.131:8848
      namespace: seata_namespace_id
      group: SEATA_GROUP